### PR TITLE
Add textAlign argument

### PR DESCRIPTION
**Pull request by dnadawa**
- Add textAlign argument to the _dialog.show() function.
- Update the Readme

### CODE REVIEW

**Review by ajomuch92 — APPROVED** [review]

**Comment by ajomuch92** [comment]
On next day I will publish a new version @dnadawa, thanks for your contribution

**Comment by dnadawa** [comment]
Sure. Happy to contribute.

**Comment by ajomuch92** [comment]
New version published. @dnadawa

**Comment by dnadawa** [comment]
Great

**Pull request merged**
